# SPDX-FileCopyrightText: Copyright (c) 2026 Alexey Sedoykin
# SPDX-License-Identifier: MIT

"""Shared orchestrator policy. Native runtime retries are a separate capability."""
import json

from src.contracts.contracts import workflow_satisfied


def retry_policy(configured=0, performed=0, native=0):
    return {'mode': 'bounded_format_repair' if configured else 'single_prompt_local_validation',
            'orchestrator_repair_attempts_configured': configured,
            'orchestrator_repair_attempts_performed': performed,
            'orchestrator_retries': performed, 'format_retries_requested': native,
            'native_enforcement_verified': False}


def required_unresolved(context):
    entries = {item['branch']: item for item in context['branches']}
    return [branch for branch in context['requested_branches']
            if not workflow_satisfied(entries.get(branch, {}), review_enabled=context.get('review_enabled', True))]


def blocked_comparison(context):
    """No accepted input: there are no model-derived comparisons to synthesize."""
    from src.reports.presentation import russian, label
    language = context.get('output_language', 'English')
    def t(r, e): return r if russian(language) else e
    entries = {item['branch']: item for item in context['branches']}
    reasons = []
    for branch in context['requested_branches']:
        item = entries.get(branch, {})
        failures = []
        for stage in (('study', 'review') if context.get('review_enabled', True) else ('study',)):
            result = item.get(stage)
            if not result:
                failures.append(stage + ': ' + t('нет валидированного опубликованного результата', 'no validated published result'))
            elif result['completion_status'] != 'COMPLETE':
                failures.append(f"{stage}: {result['completion_status']}")
        if item.get('review') and item['review'].get('verdict') != 'PASS':
            failures.append('review: ' + label(item['review'].get('verdict', 'INCONCLUSIVE'), language))
        if not failures and not workflow_satisfied(item, review_enabled=context.get('review_enabled', True)):
            failures.append(t('условия политики не выполнены', 'policy checks not satisfied'))
        reasons.append(json.dumps(branch, ensure_ascii=False) + ': ' + '; '.join(failures))
    baseline = context['baseline_branch']
    compared = [branch for branch in context['requested_branches'] if branch != baseline]
    reason = (t('Нужны пригодные исследования базовой и хотя бы одной другой ветки. ',
                'A usable baseline study and at least one other usable study are required. ')
              if context.get('result_policy') == 'compromise' else t('Ни одна ветка не удовлетворяет условиям включённых этапов. ',
              'No branch satisfies policy checks for the enabled stages. '))
    report = ('# ' + t('Сравнение недоступно', 'Comparison n/a') + ' — BLOCKED\n\n' +
              t('Сформировано оркестратором. ', 'Generated by the orchestrator. ') + reason +
              t('Сравнение моделью не запрашивалось; это не означает отсутствия различий.\n\nБазовая ветка: ',
                'No model comparison was requested; this does not mean no differences.\n\nBaseline: ') +
              json.dumps(baseline, ensure_ascii=False) + ' @ ' + context['baseline_commit'] +
              '\n\n' + t('Сравниваемые ветки: ', 'Compared branches: ') + json.dumps(compared, ensure_ascii=False) +
              '\n\n' + t('Неполные входы (включая базовую ветку):', 'Unresolved inputs (including baseline):') + '\n\n' +
              '\n'.join('- ' + reason for reason in reasons) + '\n')
    return {'task': 'architecture_comparison', 'completion_status': 'BLOCKED',
            'baseline_branch': baseline, 'baseline_commit': context['baseline_commit'],
            'compared_branches': compared, 'unresolved_branches': required_unresolved(context),
            'differences': [], 'limitations': reasons, 'report_markdown': report}
